# Generated by Django 5.2.10 on 2026-01-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_group', models.CharField(choices=[('child', '0–5 years'), ('teen', '6–18 years'), ('adult', '19–59 years'), ('senior', '60+ years')], max_length=20)),
                ('description', models.TextField()),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
    ]
