# Generated by Django 5.2.10 on 2026-01-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0003_vaccination_approved_at_vaccination_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='is_personal',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='hospital_name',
            field=models.CharField(default='Unknown Hospital', max_length=200),
            preserve_default=False,
        ),
    ]
