# Generated by Django 5.2.10 on 2026-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0004_remove_vaccination_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='is_personal',
            field=models.BooleanField(default=True),
        ),
    ]
