# Generated by Django 5.2.10 on 2026-01-24 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0005_vaccination_is_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='is_personal',
            field=models.BooleanField(default=False, help_text="True if this is user's personal vaccination history"),
        ),
    ]
