# Generated by Django 5.2.10 on 2026-02-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0006_remove_vaccination_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='hospital_name',
            field=models.CharField(default='Not specified', max_length=200),
        ),
    ]
