# Generated by Django 5.2.10 on 2026-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0007_vaccination_hospital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming'), ('overdue', 'Overdue')], default='upcoming', max_length=20),
        ),
    ]
