# Generated by Django 5.2.10 on 2026-02-11 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_diseasealert_approved_at_diseasealert_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alternative_names', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('viral', 'Viral'), ('bacterial', 'Bacterial'), ('fungal', 'Fungal'), ('genetic', 'Genetic'), ('chronic', 'Chronic'), ('skin', 'Skin'), ('other', 'Other')], max_length=50)),
                ('body_system', models.CharField(max_length=100)),
                ('first_identified_year', models.CharField(blank=True, max_length=50)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('causes', models.TextField()),
                ('symptoms', models.TextField()),
                ('risk_factors', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('transmission_type', models.CharField(blank=True, max_length=200)),
                ('incubation_period', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('treatment', models.TextField()),
                ('medicines', models.TextField(blank=True)),
                ('home_remedies', models.TextField(blank=True)),
                ('prevention', models.TextField(blank=True)),
                ('lifestyle_changes', models.TextField(blank=True)),
                ('specialist_required', models.CharField(blank=True, max_length=200)),
                ('is_vaccine_available', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diseases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
