# Generated by Django 5.2.10 on 2026-02-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='is_contagious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
