# Generated by Django 5.2.10 on 2026-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0004_disease_history_disease_is_contagious_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='specialist_required',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
