# Generated by Django 5.2.10 on 2026-02-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0005_alter_disease_specialist_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='hospital_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
