# Generated by Django 5.2.10 on 2026-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0006_disease_hospital_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='alternative_names',
            new_name='alternative_names_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='body_system',
            new_name='body_system_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='risk_level',
            new_name='body_system_hi',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='causes',
            new_name='causes_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='history',
            new_name='causes_hi',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='complications',
            new_name='complications_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='home_remedies',
            new_name='home_remedies_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='incubation_period',
            new_name='incubation_period_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='lifestyle_changes',
            new_name='lifestyle_changes_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='medicines',
            new_name='medicines_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='name',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='specialist_required',
            new_name='name_hi',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='origin',
            new_name='origin_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='prevention',
            new_name='prevention_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='risk_factors',
            new_name='risk_factors_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='symptoms',
            new_name='symptoms_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='transmission_type',
            new_name='transmission_type_en',
        ),
        migrations.RenameField(
            model_name='disease',
            old_name='treatment',
            new_name='treatment_en',
        ),
        migrations.RenameField(
            model_name='diseasealert',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='diseasealert',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='disease',
            name='alternative_names_hi',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='alternative_names_te',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='body_system_te',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='causes_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='complications_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='complications_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='history_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='history_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='history_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='home_remedies_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='home_remedies_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='incubation_period_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='incubation_period_te',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='lifestyle_changes_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='lifestyle_changes_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='medicines_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='medicines_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_te',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='origin_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='origin_te',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_factors_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_factors_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_level_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_level_hi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='risk_level_te',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='specialist_required_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='specialist_required_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='specialist_required_te',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='transmission_type_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='transmission_type_te',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='description_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diseasealert',
            name='title_te',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
