# Generated by Django 5.2.10 on 2026-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0007_rename_alternative_names_disease_alternative_names_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='alternative_names_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
