# Generated by Django 5.2.10 on 2026-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0008_alter_disease_alternative_names_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='first_identified_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
