# Generated by Django 5.2.10 on 2026-02-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0009_alter_disease_first_identified_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='complications_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
