# Generated by Django 5.2.10 on 2026-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0010_alter_disease_complications_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='incubation_period_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='lifestyle_changes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='medicines_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
