# Generated by Django 5.2.10 on 2026-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0011_alter_disease_incubation_period_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='body_system_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='origin_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
