# Generated by Django 5.2.10 on 2026-02-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0012_alter_disease_body_system_en_alter_disease_origin_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='risk_factors_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
