# Generated by Django 5.2.10 on 2026-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0013_alter_disease_risk_factors_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='transmission_type_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
