# Generated by Django 5.2.10 on 2026-02-16 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0014_alter_disease_transmission_type_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_te', models.CharField(max_length=100)),
                ('name_hi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='disease',
            name='home_remedies_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='prevention_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseasealert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.location'),
        ),
    ]
