# Generated by Django 5.2.10 on 2026-02-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_location'),
        ('diseases', '0015_location_alter_disease_home_remedies_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasealert',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
