# Generated by Django 5.2.10 on 2026-02-10 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('disease_added', 'Disease Added'), ('vaccination_added', 'Vaccination Added'), ('vaccination_completed', 'Vaccination Completed'), ('quiz_attempted', 'Quiz Attempted'), ('quiz_created', 'Quiz Created'), ('chatbot_chat', 'Chatbot Interaction'), ('personal_vaccination', 'Personal Vaccination Added'), ('notification_received', 'Notification Received')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_app', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
