# Generated by Django 5.2.10 on 2026-02-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type_notification_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='message_en',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='notification',
            name='message_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_te',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_te',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
